name: Call WorkFlow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: [trigger-maven-build]
  workflow_dispatch:

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Java CI workflow in another repository
        id: trigger-java-ci
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: souravdasbitm/JavaSeleniumRestAssured
          event-type: trigger-maven-build

      - name: Get status of triggered workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          runId=${{ steps.trigger-java-ci.outputs.run_id }}
          for i in {1..10}; do
            status=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/souravdasbitm/JavaSeleniumRestAssured/actions/runs/$runId \
              | jq '.status')
            if [ "$status" != "null" ]; then
              echo "Workflow status: $status"
              break
            fi
            sleep 10
          done
