name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Call the called workflow
        uses: actions/runner@v2
        with:
          token: ${{ secrets.PAT }}
          url: https://github.com/souravdasbitm/JavaSeleniumRestAssured
          name: Runner
          ref: main
          path:.github/workflows/called_workflow.yml
          event: workflow_dispatch
      - name: Get the status of the called workflow
        run: |
          status=$(git -C.github/workflows/ output --name=status)
          echo "The status of the called workflow is: $status"
